### ISSUE TITLE
Is this a drop-in replacement for the nginx-vhosts plugin?

### ISSUE THREAD

**Issue by josegonzalez** [256dpi/dokku-haproxy#3]
Just curious, would be nice if it was :)

**Comment by 256dpi** [comment]
Kind of... ;) I would need to test that thoroughly. 

The plugin is not very mature as it was hacked together to enable other protocols than http to be used by an app. Personally, I wouldn't suggest to replace the nginx setup with haproxy for http traffic as the nginx configuration might be more solid regarding security and such?

**Comment by josegonzalez** [comment]
Got it, just checking. I added it to our plugins page, btw :)

**Comment by josegonzalez** [comment]
Note: in our upcoming 0.5.x, we added a feature to swap out the load balancer in use for a particular application, inspired by this plugin :)

**Comment by 256dpi** [comment]
Cool! :+1:

Would it make sense to transfer the plugin to the dokku organization in order to open it to more contributions and better integration?

**Comment by josegonzalez** [comment]
If you can get it to a state where it implements mosts/all of our nginx proxy features, then yeah, we can do that.
