### ISSUE TITLE
Lowest supported Dokku version?

### ISSUE THREAD

**Issue by RickCarlino** [256dpi/dokku-haproxy#5]
Hi,

I have two servers: One was running `0.3.13` and the other one was running the edge version of Dokku.

Upgrading fixed the issue, but I was curious to know what the lowest supported version was. I could do a PR to update the docs accordingly if you would like.

**Comment by 256dpi** [comment]
Hi @RickCarlino,

I don't really know how far back the compatibility would go. My guess is that you need at least the 0.4.x series of dokku. But in the Readme I would recommend to use 0.5.x. What do you think?

**Comment by RickCarlino** [comment]
Sounds good. I just opened [PR #6 ](https://github.com/256dpi/dokku-haproxy/pull/6) please let me know if it needs any formatting fixes. Thanks for maintaining this plugin.
