### ISSUE TITLE
Compatibility status with 0.6

### ISSUE THREAD

**Issue by RickCarlino** [256dpi/dokku-haproxy#7]
Hi,

I just upgraded a machine to `0.6.0` and can't get this plugin to work the way it used. It looks like a lot has changed in this version with regards to port exposure.

Is anyone running this plugin on 0.6.0? Just wanted to make sure I'm not getting ahead of myself by running this on 0.6.0.

**Comment by 256dpi** [comment]
Yes, this plugin is still based on the 0.5.X version of dokku. It probably won't work with 0.6.0. I might update this in the next couple of months, but I can't guarantee it...

**Comment by RickCarlino** [comment]
Thanks for the quick response!
